
#ifndef __MPR_ID_MAP_H__
#define __MPR_ID_MAP_H__

#include <stdint.h>
#include "util/mpr_inline.h"

/*! Bit flags for indicating instance `id_pair` status. */
#define UPDATED           0x01
#define RELEASED_LOCALLY  0x02
#define RELEASED_REMOTELY 0x04

typedef struct _mpr_id_map *mpr_id_map;
typedef uint64_t mpr_id;

mpr_id_map mpr_id_map_new();

void mpr_id_map_free(mpr_id_map map);

// TODO: also move this struct into id_map.c
/*! The instance ID map is a linked list of int32 instance ids for coordinating
 *  remote and local instances. */
typedef struct _mpr_id_pair {
    struct _mpr_id_pair *next;      /*!< The next id map in the list. */

    union {
        uint64_t global;            /*!< Global instance id (generated by originating device). */
        struct _mpr_id_pair *parent;
    };
    uint64_t local;                 /*!< Local instance id. */
    union {
        struct {
            int16_t local;
            int16_t global;
        } refcount;
        void *data;
    };
    uint8_t status;
    uint8_t indirect;
} mpr_id_pair_t, *mpr_id_pair;

MPR_INLINE static void mpr_ids_incref_local(mpr_id_pair ids)
{
    ++ids->refcount.local;
}

MPR_INLINE static void mpr_ids_incref_global(mpr_id_pair ids)
{
    ++ids->refcount.global;
}

MPR_INLINE static int mpr_ids_getref_local(mpr_id_pair ids)
{
    return ids->refcount.local;
}

MPR_INLINE static int mpr_ids_getref_global(mpr_id_pair ids)
{
    return ids->refcount.global;
}

// add count to reserve?
void mpr_id_map_reserve(mpr_id_map map);

int mpr_id_map_decref_local(mpr_id_map map, mpr_id_pair ids);

int mpr_id_map_decref_global(mpr_id_map map, mpr_id_pair ids);

mpr_id_pair mpr_id_map_add(mpr_id_map map, mpr_id local, mpr_id global, int indirect);

mpr_id_pair mpr_id_map_get_first(mpr_id_map map);

// rename as 'get_GID'
mpr_id_pair mpr_id_map_get_local(mpr_id_map map, mpr_id id);

mpr_id_pair mpr_id_map_get_global(mpr_id_map map, mpr_id id);

/* TODO: rename this function */
mpr_id_pair mpr_id_map_get_global_free(mpr_id_map map, mpr_id last_id);

int mpr_id_map_get_size(mpr_id_map map, int active);

void mpr_id_map_remove(mpr_id_map map, mpr_id_pair rem);

#ifdef DEBUG
void mpr_id_map_print(mpr_id_map map);
#endif

#endif /* __MPR_ID_MAP_H__ */
